model:
  name: Tripmodel
  input_channels: 3
  num_classes: 1
optimizer:
  type: Adam
  learning_rate: 0.0001
  weight_decay: 1.0e-08
  eps: 1.0e-08
loss:
  type: MultiTaskLoss
  alpha: 0.6
  beta: 0.4
training:
  epochs: 100
  batch_size: 2
  validation_percent: 10.0
hardware:
  device: cuda:0
  gpu_id: 0
  num_workers: 0
paths:
  image_dir: F:\Bo Yu\data\HL\train\add\cloud_occlusion/
  boundary_dir: F:\Bo Yu\data\HL\train\boundary_new/
  mask_dir: F:\Bo Yu\data\HL\train\newmask/
  checkpoint_dir: F:\Bo Yu\Bsinet_yb\Mymodel\noise\HL\main64\cloud_occlusion
  log_csv: F:\Bo Yu\Bsinet_yb\Mymodel\noise\HL\main64\cloud_occlusion\LossData.csv
  log_file: F:\Bo Yu\Bsinet_yb\Mymodel\noise\HL\main64\train_image\training_main64-train_image.log
  config_file: F:\Bo Yu\Bsinet_yb\Mymodel\noise\HL\main64\train_image\model_config_main64-train_image.yaml
created_at: 2025-11-27 22:11
notes: main64-train_image
